"""Move ies to variants instead of fixtures

Revision ID: 99c5178e086a
Revises: 9debaec7630e
Create Date: 2026-09-22 13:01:22.542351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c5178e086a'
down_revision: Union[str, Sequence[str], None] = '9debaec7630e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture_variants', sa.Column('ies_file_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_fixture_variants_ies_file_id'), 'fixture_variants', ['ies_file_id'], unique=False)
    op.create_foreign_key(None, 'fixture_variants', 'assets', ['ies_file_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_fixtures_ies_file_id'), table_name='fixtures')
    op.drop_constraint(op.f('fixtures_ies_file_id_fkey'), 'fixtures', type_='foreignkey')
    op.drop_column('fixtures', 'ies_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('ies_file_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fixtures_ies_file_id_fkey'), 'fixtures', 'assets', ['ies_file_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_fixtures_ies_file_id'), 'fixtures', ['ies_file_id'], unique=False)
    op.drop_constraint(None, 'fixture_variants', type_='foreignkey')
    op.drop_index(op.f('ix_fixture_variants_ies_file_id'), table_name='fixture_variants')
    op.drop_column('fixture_variants', 'ies_file_id')
    # ### end Alembic commands ###
