"""Assets and Fixtures tables

Revision ID: 9debaec7630e
Revises: 
Create Date: 2026-09-06 16:20:22.054363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9debaec7630e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ies_file_id', sa.Uuid(), nullable=False),
    sa.Column('is_main_solution', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('applications', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("applications <@ ARRAY['interior', 'industrial']::text[]", name='ck_fixtures_applications_allowed'),
    sa.CheckConstraint("cardinality(applications) = 1 OR (applications @> ARRAY['interior']::text[] AND applications @> ARRAY['industrial']::text[])", name='ck_fixtures_applications_unique'),
    sa.CheckConstraint('cardinality(applications) <= 2', name='ck_fixtures_applications_max'),
    sa.CheckConstraint('cardinality(applications) >= 1', name='ck_fixtures_applications_nonempty'),
    sa.ForeignKeyConstraint(['ies_file_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fixtures_applications', 'fixtures', ['applications'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_fixtures_ies_file_id'), 'fixtures', ['ies_file_id'], unique=False)
    op.create_index(op.f('ix_fixtures_is_main_solution'), 'fixtures', ['is_main_solution'], unique=False)
    op.create_table('fixture_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('chip', sa.String(), nullable=False),
    sa.Column('driver', sa.String(), nullable=False),
    sa.Column('power_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('cri', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('efficacy', sa.Integer(), nullable=False),
    sa.Column('mechanical_protections', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('electrical_protections', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('dimension_length', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('dimension_width', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('dimension_depth', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('dimension_radius', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('model_3d_file_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("electrical_protections <@ ARRAY['OV', 'OC', 'OT']::text[]", name='ck_fixture_variants_electrical_allowed'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_3d_file_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'name', name='uq_fixture_variants_fixture_id_name')
    )
    op.create_index(op.f('ix_fixture_variants_fixture_id'), 'fixture_variants', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_variants_model_3d_file_id'), 'fixture_variants', ['model_3d_file_id'], unique=False)
    op.create_table('fixture_variant_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('image_file_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['image_file_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['fixture_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'image_file_id', name='uq_fixture_variant_images_variant_file')
    )
    op.create_index(op.f('ix_fixture_variant_images_image_file_id'), 'fixture_variant_images', ['image_file_id'], unique=False)
    op.create_index(op.f('ix_fixture_variant_images_variant_id'), 'fixture_variant_images', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixture_variant_images_variant_id'), table_name='fixture_variant_images')
    op.drop_index(op.f('ix_fixture_variant_images_image_file_id'), table_name='fixture_variant_images')
    op.drop_table('fixture_variant_images')
    op.drop_index(op.f('ix_fixture_variants_model_3d_file_id'), table_name='fixture_variants')
    op.drop_index(op.f('ix_fixture_variants_fixture_id'), table_name='fixture_variants')
    op.drop_table('fixture_variants')
    op.drop_index(op.f('ix_fixtures_is_main_solution'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_ies_file_id'), table_name='fixtures')
    op.drop_index('ix_fixtures_applications', table_name='fixtures', postgresql_using='gin')
    op.drop_table('fixtures')
    op.drop_table('assets')
    # ### end Alembic commands ###
